/*
 * Do not edit this file.  It is automatically generated by generate-patterns.pl
 * based on xpm image files in the "patterns" subdirectory.  Any changes here
 * may be overwritten.
*/

enum_start (gegl_video_degradation_type)
    enum_value (GEGL_VIDEO_DEGRADATION_TYPE_SQUARE_PINWHEEL, "square-pinwheel",
        N_("Square-pinwheel"))
    enum_value (GEGL_VIDEO_DEGRADATION_TYPE_STAGGERED_2X3, "staggered-2x3",
        N_("Staggered-2x3"))
enum_end (GeglVideoDegradationPlusType)

property_enum (pattern, _("Pattern"), GeglVideoDegradationPlusType,
    gegl_video_degradation_type, GEGL_VIDEO_DEGRADATION_TYPE_SQUARE_PINWHEEL)
description (_("Type of RGB pattern to use"))
