/*
 * Do not edit this file.  It is automatically generated based on xpm image
 * files in the "patterns" subdirectory.  Any changes here may be overwritten.
*/


gint square_pinwheel_vixmap[7*17] = {
     -1,  -1,  -1,  -1,   1,   1,  -1,
     -1,   2,   2,   0,   1,   1,  -1,
     -1,   2,   2,   3,   3,   0,  -1,
      4,   4,   0,   3,   3,   5,   5,
      4,   4,   6,   6,   0,   5,   5,
     -1,   0,   6,   6,   7,   7,  -1,
     -1,   8,   8,   0,   7,   7,  -1,
     -1,   8,   8,   9,   9,   0,  -1,
     10,  10,   0,   9,   9,  11,  11,
     10,  10,  12,  12,   0,  11,  11,
     -1,   0,  12,  12,  13,  13,  -1,
     -1,  14,  14,   0,  13,  13,  -1,
     -1,  14,  14,  15,  15,   0,  -1,
     16,  16,   0,  15,  15,  17,  17,
     16,  16,  18,  18,   0,  17,  17,
     -1,   0,  18,  18,  19,  19,  -1,
     -1,  -1,  -1,  -1,  19,  19,  -1,
};
gint square_pinwheel_colmap[20] = {
      0,   1,   2,   3,   1,   1,   2,   3,   1,   2,
      3,   3,   1,   2,   3,   1,   2,   2,   3,   1,
};
Pattern square_pinwheel = {
    1, 1, 5, 15, 20, square_pinwheel_vixmap, 7, 17, square_pinwheel_colmap
};

gint staggered_2x3_vixmap[4*12] = {
     -1,  -1,   6,   6,
      4,   4,   6,   6,
      4,   4,   6,   6,
      4,   4,   7,   7,
      3,   3,   7,   7,
      3,   3,   7,   7,
      3,   3,   1,   1,
      5,   5,   1,   1,
      5,   5,   1,   1,
      5,   5,   2,   2,
     -1,  -1,   2,   2,
     -1,  -1,   2,   2,
};
gint staggered_2x3_colmap[8] = {
      0,   1,   2,   2,   1,   3,   2,   3,
};
Pattern staggered_2x3 = {
    0, 1, 4, 9, 8, staggered_2x3_vixmap, 4, 12, staggered_2x3_colmap
};

static Pattern *patterns[2] = { &square_pinwheel, &staggered_2x3, };
